version: "3"

services:
  weatherappp:
    container_name: front-end
    working_dir: /usr/app
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
