version: "3"

services:
  weatherappp:
    image: weatherapp_weatherappp
    container_name: front-end
    working_dir: /usr/app
    # build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    command: yarn start
  storybook:
    image: weatherapp_weatherappp
    container_name: storybook
    working_dir: /usr/app
    # build: ./
    ports:
      - "9009:9009"
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    command: yarn storybook
